
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.main.acme]
  email = "clement@champouillon.com"
  storage = "acme.json"
  [certificatesResolvers.main.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"




[api]
  insecure = true

[providers.docker]
