name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List files
        run: ls

      - name: Copy files to server
        run: rsync . $SSH_USERNAME:$SSH_PASSWORD@minecraft.homeunix.org:/home/cchampou/allixo-docker
        env:
          SSH_USERNAME: ${{ secrets.ALLIXO_USERNAME }}
          SSH_PASSWORD: ${{ secrets.ALLIXO_PASSWORD }}

