name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List files
        run: ls

      - name: Copy files to server
        run: rsync . cchampou@minecraft.homeunix.org:/home/cchampou/allixo-docker
      
        #- name: Run a multi-line script
        #run: |
          #  echo Add other actions to build,
          #  echo test, and deploy your project.

